### ISSUE TITLE
Should fix a bug, jump address or call address

### ISSUE THREAD

**Issue by skychips** [GrammaTech/mc-asm#1]
In the default execution of

__asm__(
R"(
mov %eax, %eax
call 0x12345678
)"
);

```
[
  {
    "kind": "changeSection",
    "section": {
      "alignment": 1,
      "characteristics": 1610612768,
      "class": "MCSectionCOFF",
      "isVirtual": false,
      "kind": {
        "isBSS": false,
        "isCommon": false,
        "isData": false,
        "isExecuteOnly": false,
        "isGlobalWriteableData": false,
        "isMergeableCString": false,
        "isMergeableConst": false,
        "isMetadata": false,
        "isReadOnly": false,
        "isReadOnlyWithRel": false,
        "isText": true,
        "isThreadBSS": false,
        "isThreadLocal": false,
        "isWriteable": false
      },
      "name": ".text"
    }
  },
  {
    "data": "89c0",
    "fixups": [],
    "inst": {
      "desc": {
        "canFoldAsLoad": false,
        "hasDelaySlot": false,
        "hasOptionalDef": false,
        "hasUnmodeledSideEffects": false,
        "implicitDefs": [],
        "implicitUses": [],
        "isAdd": false,
        "isAuthenticated": false,
        "isBarrier": false,
        "isBitcast": false,
        "isBranch": false,
        "isCall": false,
        "isCompare": false,
        "isConditionalBranch": false,
        "isConvergent": false,
        "isExtractSubregLike": false,
        "isIndirectBranch": false,
        "isInsertSubregLike": false,
        "isMoveImmediate": false,
        "isMoveReg": true,
        "isNotDuplicable": false,
        "isPredicable": false,
        "isPseudo": false,
        "isRegSequenceLike": false,
        "isReturn": false,
        "isSelect": false,
        "isTerminator": false,
        "isTrap": false,
        "isUnconditionalBranch": false,
        "isVariadic": false,
        "mayLoad": false,
        "mayRaiseFPException": false,
        "mayStore": false,
        "numDefs": 1,
        "variadicOpsAreDefs": false
      },
      "flags": 0,
      "opcode": "MOV32rr",
      "operands": [
        {
          "kind": "reg",
          "reg": "EAX"
        },
        {
          "kind": "reg",
          "reg": "EAX"
        }
      ]
    },
    "kind": "instruction"
  },
  {
    "data": "e800000000",
    "fixups": [
      {
        "flags": [
          "IsPCRel"
        ],
        "name": "FK_PCRel_4",
        "offset": 1,
        "targetOffset": 0,
        "targetSize": 32,
        "value": {
          "kind": "binaryExpr",
          "lhs": {
            "kind": "constant",
            "useHexFormat": false,
            "value": 305419896
          },
          "opcode": "Add",
          "rhs": {
            "kind": "constant",
            "useHexFormat": false,
            "value": -4
          }
        }
      }
    ],
    "inst": {
      "desc": {
        "canFoldAsLoad": false,
        "hasDelaySlot": false,
        "hasOptionalDef": false,
        "hasUnmodeledSideEffects": false,
        "implicitDefs": [],
        "implicitUses": [
          "ESP",
          "SSP"
        ],
        "isAdd": false,
        "isAuthenticated": false,
        "isBarrier": false,
        "isBitcast": false,
        "isBranch": false,
        "isCall": true,
        "isCompare": false,
        "isConditionalBranch": false,
        "isConvergent": false,
        "isExtractSubregLike": false,
        "isIndirectBranch": false,
        "isInsertSubregLike": false,
        "isMoveImmediate": false,
        "isMoveReg": false,
        "isNotDuplicable": false,
        "isPredicable": false,
        "isPseudo": false,
        "isRegSequenceLike": false,
        "isReturn": false,
        "isSelect": false,
        "isTerminator": false,
        "isTrap": false,
        "isUnconditionalBranch": false,
        "isVariadic": false,
        "mayLoad": false,
        "mayRaiseFPException": false,
        "mayStore": false,
        "numDefs": 0,
        "variadicOpsAreDefs": false
      },
      "flags": 0,
      "opcode": "CALLpcrel32",
      "operands": [
        {
          "imm": 305419896,
          "kind": "imm"
        }
      ]
    },
    "kind": "instruction"
  }
]

```

The actual address of the generated assembly code is 0x00000000

The module address is missing here, so llvm does not calculate the address that should be called correctly.

Or maybe I don't use ATT or INTEL assembly syntax.

Please advise me

Thank you very much!

**Comment by jranieri-grammatech** [comment]
This is the correct behavior.

Call and jmp addresses are PC-relative, so LLVM can't just embed the address in the encoding because it doesn't know the runtime address of the call instruction. Instead, it puts the information in the fixups list and it's up to you to deal with this in some way.

Assuming you know where the instructions will get loaded into memory, you should be able to iterate over the fixups for the instruction and modify the instruction bytes accordingly.

**Comment by skychips** [comment]
> This is the correct behavior.
> 
> Call and jmp addresses are PC-relative, so LLVM can't just embed the address in the encoding because it doesn't know the runtime address of the call instruction. Instead, it puts the information in the fixups list and it's up to you to deal with this in some way.
> 
> Assuming you know where the instructions will get loaded into memory, you should be able to iterate over the fixups for the instruction and modify the instruction bytes accordingly.

Roger, so please, is there an example of a mini-minimal version, I would like to learn from you how to implement that functionality.

**Comment by skychips** [comment]
When I type jmp 0x12345678, it compiles "eb 00" instead of "e9 00 00 00 00".

How can I deal with this situation? Please let me know. Thank you very much.

**Comment by jranieri-grammatech** [comment]
> When I type jmp 0x12345678, it compiles "eb 00" instead of "e9 00 00 00 00".
> 
> How can I deal with this situation? Please let me know. Thank you very much.

Good question! This is usually taken care of by [relaxation](https://eli.thegreenplace.net/2013/01/03/assembler-relaxation), but that's done during object file generation and mc-asm only runs the assembly parser. Thankfully there is a way to [force the instruction encoding you want by using the `{disp32}` prefix](https://sourceware.org/binutils/docs/as/i386_002dMnemonics.html).

So this would look like:
```asm
{disp32} jmp 0x12345678
````

**Comment by jranieri-grammatech** [comment]
> > This is the correct behavior.
> > Call and jmp addresses are PC-relative, so LLVM can't just embed the address in the encoding because it doesn't know the runtime address of the call instruction. Instead, it puts the information in the fixups list and it's up to you to deal with this in some way.
> > Assuming you know where the instructions will get loaded into memory, you should be able to iterate over the fixups for the instruction and modify the instruction bytes accordingly.
> 
> Roger, so please, is there an example of a mini-minimal version, I would like to learn from you how to implement that functionality.

Something like this should get you started:
```python
import typing

def evaluate_constant_expr(expr: dict) -> int:
    kind = expr["kind"]
    
    if kind == "binaryExpr":
        lhs = evaluate_constant_expr(expr["lhs"])
        rhs = evaluate_constant_expr(expr["rhs"])

        opcode = expr["opcode"]
        if opcode == "Add":
            return lhs + rhs

    elif kind == "constant":
        return expr["value"]

    assert False, "unsupported constant expression"


def apply_one_fixup(data: bytearray, fixup: dict, runtime_addr: int) -> None:
    name = fixup["name"]

    if name == "FK_PCRel_4":
        offset = fixup["offset"]
        target = evaluate_constant_expr(fixup["value"])
        rel_addr = target - runtime_addr - offset
        data[offset:offset+4] = rel_addr.to_bytes(4, 'little', signed=True)
    
    else:
        assert False, "unsupported fixup type"


def apply_fixups(insts: typing.Iterable[dict], runtime_addr: int):
    for inst in insts:
        if inst["kind"] == "instruction":
            data = bytearray.fromhex(inst["data"])
            for fixup in inst["fixups"]:
                apply_one_fixup(data, fixup, runtime_addr)

            inst["data"] = data.hex()
            runtime_addr += len(data)
```

**Comment by skychips** [comment]
> > > This is the correct behavior.
> > > Call and jmp addresses are PC-relative, so LLVM can't just embed the address in the encoding because it doesn't know the runtime address of the call instruction. Instead, it puts the information in the fixups list and it's up to you to deal with this in some way.
> > > Assuming you know where the instructions will get loaded into memory, you should be able to iterate over the fixups for the instruction and modify the instruction bytes accordingly.
> > 
> > 
> > Roger, so please, is there an example of a mini-minimal version, I would like to learn from you how to implement that functionality.
> 
> Something like this should get you started:
> 
> ```python
> import typing
> 
> def evaluate_constant_expr(expr: dict) -> int:
>     kind = expr["kind"]
>     
>     if kind == "binaryExpr":
>         lhs = evaluate_constant_expr(expr["lhs"])
>         rhs = evaluate_constant_expr(expr["rhs"])
> 
>         opcode = expr["opcode"]
>         if opcode == "Add":
>             return lhs + rhs
> 
>     elif kind == "constant":
>         return expr["value"]
> 
>     assert False, "unsupported constant expression"
> 
> 
> def apply_one_fixup(data: bytearray, fixup: dict, runtime_addr: int) -> None:
>     name = fixup["name"]
> 
>     if name == "FK_PCRel_4":
>         offset = fixup["offset"]
>         target = evaluate_constant_expr(fixup["value"])
>         rel_addr = target - runtime_addr - offset
>         data[offset:offset+4] = rel_addr.to_bytes(4, 'little', signed=True)
>     
>     else:
>         assert False, "unsupported fixup type"
> 
> 
> def apply_fixups(insts: typing.Iterable[dict], runtime_addr: int):
>     for inst in insts:
>         if inst["kind"] == "instruction":
>             data = bytearray.fromhex(inst["data"])
>             for fixup in inst["fixups"]:
>                 apply_one_fixup(data, fixup, runtime_addr)
> 
>             inst["data"] = data.hex()
>             runtime_addr += len(data)
> ```

Thank you very much, you have worked hard.

Next, I will follow your method to fix those problems that existed before.
